"""No-JVP engineering preflight for Family A source-native latent actions.

This program deliberately performs **no** dataset access, calibration,
held-out measurement, training, reward evaluation, or phenomenon scoring.  It
checks only the minimum runtime fact needed by the redesigned P1 route:

1. several fixed-seed actions generated by the pinned official Gumbel sampler
   are genuine continuous first latent actions under the real SGLang request
   semantics; and
2. after conditioning on each such action, a paired forward-only
   sample/reference-teacher-force path can be executed with independent KV
   caches and a shared visible history.

The test-only boundary after a short deterministic latent suffix is sometimes
forced to token 524.  That makes the visible sample/force plumbing testable on
a small synthetic prompt.  It is *not* a natural rollout, an estimate of the
P1 continuation-risk estimand, evidence of a Horizon Gap, or a calibration
result.  A later separately reviewed P1 protocol must define and validate its
own action-conditioned latent suffix law.

Run only in the pinned WSL runtime, from the repository root:

    /home/lixingshuo/.venvs/latentgrpo-py311/bin/python -m \
      research.behavioral_geometry.p1_forward_action_preflight
"""

from __future__ import annotations

import argparse
import json
import sys
import time
from dataclasses import asdict, dataclass
from pathlib import Path
from types import SimpleNamespace
from typing import Any

import torch
from transformers import AutoModelForCausalLM, AutoTokenizer, __version__ as transformers_version

from research.behavioral_geometry.p1_official_sampler_replay import (
    OfficialSamplerReplay,
    replay_pinned_sampler_on_fake_request,
)
from research.behavioral_geometry.p1_forward_kl_contract import (
    ContinuationEndpoint,
    audit_endpoint_pair,
    paired_path_kl,
)
from research.behavioral_geometry.p1_source_sampler_contract import SourceLatentSamplerConfig


MODEL_DIR = Path("/mnt/e/LantentGRPO/_models/Latent-GRPO-Llama-1B")
SOURCE_END_ID = 524
MODEL_VOCAB_SIZE = 128256
FORBIDDEN_TOKENIZER_ONLY_ID = 128256

# Source-format synthetic content, fixed before execution. It is not taken from
# a dataset and no answer or reward is inspected. The checkpoint's own chat
# template adds the assistant header and <think> marker used by official eval.
PROMPT_NAME = "synthetic_arithmetic_source_format"
PROMPT_USER_TEXT = (
    "Please reason step by step, and put your final answer within \\boxed{}.\n"
    "A box contains 2 red counters and 3 blue counters. How many counters are in the box?"
)

# These seeds, latent prefix length, and visible test horizon are constants of
# this engineering check, defined before this script is executed.  No result
# may add seeds, change a prompt, or lengthen a path to create a favorable
# action bank.
ACTION_SEEDS = (2026071601, 2026071602, 2026071603, 2026071604)
VISIBLE_FORWARD_SEED = 2026071699
VISIBLE_REVERSE_SEED = 2026071700
VISIBLE_IDENTITY_SEED = 2026071701
VISIBLE_BENCHMARK_SEED = 2026071703
BENCHMARK_FORCE_TOKEN_ID = 220
TOPK = 10
CONTROL_LATENT_STEPS = 3
NATURAL_LATENT_CAP = 32
VISIBLE_TEST_HORIZON = 4
MIN_DISTINCT_ACTION_L2 = 1e-4
IDENTITY_KL_TOLERANCE = 1e-8


@dataclass
class ForwardActionPreflightResult:
    status: str
    runtime: dict[str, Any]
    protocol: dict[str, Any]
    prompt: dict[str, Any]
    action_bank: list[dict[str, Any]]
    endpoint_audit: dict[str, Any]
    identity_control: dict[str, Any]
    paired_forward_path: dict[str, Any]
    timing: dict[str, Any]
    gpu: dict[str, Any]
    failures: list[str]


def _progress(message: str) -> None:
    """Emit a monitoring-only phase marker without changing any result."""

    print(f"[p1-forward-action-preflight] {message}", file=sys.stderr, flush=True)


def _as_list(tensor: torch.Tensor) -> list[Any]:
    return tensor.detach().float().cpu().tolist()


def _cache_ptrs(past_key_values: Any) -> list[int]:
    if hasattr(past_key_values, "key_cache"):
        tensors = list(past_key_values.key_cache) + list(past_key_values.value_cache)
    elif isinstance(past_key_values, (tuple, list)):
        tensors = [tensor for layer in past_key_values for tensor in layer]
    else:
        return []
    return [int(tensor.data_ptr()) for tensor in tensors if isinstance(tensor, torch.Tensor)]


def _sampler_config(*, noise: bool) -> SourceLatentSamplerConfig:
    return SourceLatentSamplerConfig(
        max_topk=TOPK,
        top_p=1.0,
        temperature=1.0,
        gumbel_softmax_temperature=1.0,
        noise_scale=1.0,
        add_noise_gumbel_softmax=noise,
        use_one_sided_gumbel_noise=True,
        latent_mode=True,
        latent_end_token_id=SOURCE_END_ID,
    )


def _source_weighted_embedding(
    embedding_weight: torch.Tensor, token_ids: torch.Tensor, probs: torch.Tensor
) -> torch.Tensor:
    """Mirror the pinned ``weighted_forward`` soft arithmetic exactly.

    The official source multiplies FP32 ``topk_probs`` by BF16 lookup rows,
    accumulates in FP32, and casts the result back to the embedding dtype.  It
    must not first round probabilities to BF16.
    """

    if token_ids.ndim != 1 or probs.ndim != 1 or token_ids.shape != probs.shape:
        raise ValueError("source mixture ids and probabilities must be matching rank-one tensors")
    if torch.any(token_ids < 0) or torch.any(token_ids >= embedding_weight.shape[0]):
        raise ValueError("source mixture contains an invalid embedding id")
    return torch.sum(probs.float().unsqueeze(-1) * embedding_weight[token_ids], dim=0).to(
        embedding_weight.dtype
    )


def _legacy_bf16_first_embedding(
    embedding_weight: torch.Tensor, token_ids: torch.Tensor, probs: torch.Tensor
) -> torch.Tensor:
    """Diagnostic only: the less precise arithmetic used by old JVP helpers."""

    return torch.sum(
        probs.to(embedding_weight.dtype).unsqueeze(-1) * embedding_weight[token_ids], dim=0
    )


def _prefill(model, prompt_ids: tuple[int, ...]):
    input_ids = torch.tensor([prompt_ids], device="cuda", dtype=torch.long)
    return model(
        input_ids=input_ids,
        attention_mask=torch.ones_like(input_ids),
        use_cache=True,
        return_dict=True,
    )


def _step(model, past_key_values: Any, embedding: torch.Tensor, position: int):
    return model(
        inputs_embeds=embedding.reshape(1, 1, -1),
        attention_mask=torch.ones((1, position + 1), dtype=torch.long, device="cuda"),
        position_ids=torch.tensor([[position]], dtype=torch.long, device="cuda"),
        past_key_values=past_key_values,
        use_cache=True,
        return_dict=True,
    )


def _make_default_req(tokenizer, rid: str):
    """Build the actual source request with no user stop strings/tokens."""

    from sglang.srt.managers.schedule_batch import Req
    from sglang.srt.sampling.sampling_params import SamplingParams

    params = SamplingParams(max_new_tokens=128)
    params.verify()
    params.normalize(tokenizer)
    req = Req(
        rid=rid,
        origin_input_text="synthetic",
        origin_input_ids=(int(tokenizer.bos_token_id),),
        sampling_params=params,
        eos_token_ids={int(tokenizer.eos_token_id)},
        enable_latent=True,
        latent_end_token_id=SOURCE_END_ID,
        max_topk=TOPK,
    )
    req.tokenizer = tokenizer
    return req


def _proposal_logits_output(proposal: OfficialSamplerReplay) -> SimpleNamespace:
    """Shape an unmodified sampler record for ``Req.update_latent_info``."""

    return SimpleNamespace(
        topk_gumbels=proposal.topk_gumbels.unsqueeze(0).clone(),
        topk_original_probs=proposal.topk_original_probs.unsqueeze(0).clone(),
        topk_original_indices=proposal.topk_original_indices.unsqueeze(0).clone(),
        topk_probs=proposal.topk_probs.unsqueeze(0).clone(),
        topk_indices=proposal.topk_indices.unsqueeze(0).clone(),
    )


def _bool_value(value: Any) -> bool:
    return bool(value.item()) if isinstance(value, torch.Tensor) else bool(value)


def _finish_kind(req) -> str | None:
    if req.finished_reason is None:
        return None
    from sglang.srt.managers.schedule_batch import (
        FINISH_ABORT,
        FINISH_LENGTH,
        FINISH_MATCHED_STR,
        FINISH_MATCHED_TOKEN,
    )

    if isinstance(req.finished_reason, FINISH_LENGTH):
        return ContinuationEndpoint.FINISH_LENGTH.value
    if isinstance(req.finished_reason, FINISH_MATCHED_TOKEN):
        return ContinuationEndpoint.FINISH_TOKEN.value
    if isinstance(req.finished_reason, FINISH_MATCHED_STR):
        return ContinuationEndpoint.FINISH_STRING.value
    if isinstance(req.finished_reason, FINISH_ABORT):
        return ContinuationEndpoint.EXECUTION_ABORT.value
    return type(req.finished_reason).__name__


def _apply_proposal_to_req(req, proposal: OfficialSamplerReplay) -> dict[str, Any]:
    """Apply append -> check -> update to one persistent source request."""

    req.output_ids.append(proposal.next_token_id)
    req.check_finished()
    finished_after_check = req.finished()
    finish_kind = _finish_kind(req)
    req.update_latent_info(_proposal_logits_output(proposal), 0)
    latent_mode_after_update = _bool_value(req.sampling_params.latent_mode)
    actual_ids = req.topk_idx.detach().clone()
    actual_probs = req.topk_prob.detach().clone()
    expected_continuous = (
        not finished_after_check and proposal.next_token_id != SOURCE_END_ID
    )
    matches_proposed_mixture = bool(
        torch.equal(actual_ids, proposal.topk_indices)
        and torch.equal(actual_probs, proposal.topk_probs)
    )
    return {
        "proxy": proposal.next_token_id,
        "finished_after_check": bool(finished_after_check),
        "finish_kind": finish_kind,
        "request_output_length": len(req.output_ids),
        "latent_mode_after_update": latent_mode_after_update,
        "actual_topk_ids": [int(value) for value in actual_ids.detach().cpu().tolist()],
        "actual_topk_probs": _as_list(actual_probs),
        "continuous_action_consumed": bool(
            expected_continuous and latent_mode_after_update and matches_proposed_mixture
        ),
        "structural_end_consumed": bool(
            not finished_after_check
            and proposal.next_token_id == SOURCE_END_ID
            and not latent_mode_after_update
            and int(actual_ids[0].item()) == SOURCE_END_ID
            and bool(torch.all(actual_ids[1:] == -100).item())
            and float(actual_probs[0].item()) == 1.0
            and bool(torch.all(actual_probs[1:] == 0.0).item())
        ),
        "matches_proposed_mixture": matches_proposed_mixture,
    }


def _execute_under_actual_request(tokenizer, proposal: OfficialSamplerReplay, rid: str) -> dict[str, Any]:
    """One-action wrapper used only for independent action-bank admissibility."""

    return _apply_proposal_to_req(_make_default_req(tokenizer, rid), proposal)


def _sample_source_action(logits: torch.Tensor, seed: int) -> OfficialSamplerReplay:
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    return replay_pinned_sampler_on_fake_request(logits, _sampler_config(noise=True))


def _close_source_action(
    model,
    tokenizer,
    embedding_weight: torch.Tensor,
    base_output,
    prompt_length: int,
    initial_proposal: OfficialSamplerReplay,
    rid_prefix: str,
    *,
    latent_cap: int,
    force_visible_control: bool,
) -> tuple[Any, int, dict[str, Any]]:
    """Execute one action and its deterministic suffix under a persistent Req.

    Scientific closure stops only at a source-generated endpoint or the frozen
    cap. A separately labeled control may consume E_524 after its cap solely to
    exercise visible sampling and teacher forcing.
    """

    if latent_cap < 1:
        raise ValueError("latent_cap must be positive")
    req = _make_default_req(tokenizer, rid_prefix)
    output = base_output
    position = prompt_length
    proposal = initial_proposal
    records: list[dict[str, Any]] = []

    for latent_step in range(latent_cap):
        execution = _apply_proposal_to_req(req, proposal)
        record = {
            "latent_step": latent_step,
            "proxy": proposal.next_token_id,
            "finished_after_check": execution["finished_after_check"],
            "finish_kind": execution["finish_kind"],
            "request_output_length": execution["request_output_length"],
            "continuous_action_consumed": execution["continuous_action_consumed"],
            "structural_end_consumed": execution["structural_end_consumed"],
        }
        records.append(record)
        if execution["finished_after_check"]:
            endpoint = execution["finish_kind"] or ContinuationEndpoint.EXECUTION_ABORT.value
            return output, position, {
                "endpoint": endpoint,
                "natural_visible": False,
                "forced_visible_control": False,
                "records": records,
                "request_output_ids": [int(value) for value in req.output_ids],
            }
        if execution["structural_end_consumed"]:
            output = _step(
                model, output.past_key_values, embedding_weight[SOURCE_END_ID], position
            )
            position += 1
            return output, position, {
                "endpoint": ContinuationEndpoint.NATURAL_VISIBLE.value,
                "natural_visible": True,
                "forced_visible_control": False,
                "records": records,
                "request_output_ids": [int(value) for value in req.output_ids],
            }
        if not execution["continuous_action_consumed"]:
            raise RuntimeError(
                f"latent step {latent_step} is neither terminal nor consumable: {execution}"
            )
        embedding = _source_weighted_embedding(
            embedding_weight, proposal.topk_indices, proposal.topk_probs
        )
        output = _step(model, output.past_key_values, embedding, position)
        position += 1
        proposal = replay_pinned_sampler_on_fake_request(
            output.logits[0, -1], _sampler_config(noise=False)
        )

    if force_visible_control:
        output = _step(
            model, output.past_key_values, embedding_weight[SOURCE_END_ID], position
        )
        position += 1
        return output, position, {
            "endpoint": ContinuationEndpoint.FORCED_VISIBLE_CONTROL.value,
            "natural_visible": False,
            "forced_visible_control": True,
            "records": records,
            "request_output_ids": [int(value) for value in req.output_ids],
        }

    return output, position, {
        "endpoint": ContinuationEndpoint.LATENT_TIMEOUT.value,
        "natural_visible": False,
        "forced_visible_control": False,
        "records": records,
        "request_output_ids": [int(value) for value in req.output_ids],
    }


def _paired_visible_sample_and_force(
    model,
    embedding_weight: torch.Tensor,
    reference_output,
    reference_position: int,
    candidate_output,
    candidate_position: int,
    eos_token_id: int,
    *,
    sample_seed: int,
    horizon: int,
) -> dict[str, Any]:
    """Sample only from the reference and teacher-force that exact history.

    This is an engineering instance of the chain-rule identity's mechanics.  It
    is deliberately restricted to synthetic text and an artificial test
    boundary, so the returned KL values have no scientific interpretation.
    """

    generator = torch.Generator(device="cuda")
    generator.manual_seed(sample_seed)
    ref_current = reference_output
    cand_current = candidate_output
    ref_position = reference_position
    cand_position = candidate_position
    token_ids: list[int] = []
    reference_logits: list[torch.Tensor] = []
    candidate_logits: list[torch.Tensor] = []
    eos_terminated = False

    for _ in range(horizon):
        ref_logits = ref_current.logits[0, -1]
        cand_logits = cand_current.logits[0, -1]
        reference_logits.append(ref_logits.detach())
        candidate_logits.append(cand_logits.detach())
        next_token = int(
            torch.multinomial(torch.softmax(ref_logits.float(), dim=-1), 1, generator=generator)
            .item()
        )
        if not 0 <= next_token < MODEL_VOCAB_SIZE:
            raise RuntimeError("reference sampler selected a token outside model vocabulary")
        token_ids.append(next_token)
        if next_token == eos_token_id:
            eos_terminated = True
            break
        token_embedding = embedding_weight[next_token]
        ref_current = _step(model, ref_current.past_key_values, token_embedding, ref_position)
        cand_current = _step(model, cand_current.past_key_values, token_embedding, cand_position)
        ref_position += 1
        cand_position += 1

    path_kl = paired_path_kl(torch.stack(reference_logits), torch.stack(candidate_logits))
    return {
        "visible_policy": "fixed full-vocabulary categorical temperature=1 engineering law",
        "sample_seed": sample_seed,
        "requested_horizon": horizon,
        "shared_reference_token_ids": token_ids,
        "per_step_directional_kl": path_kl.per_step.detach().cpu().tolist(),
        "sum_directional_kl": path_kl.total,
        "eos_terminated": eos_terminated,
        "teacher_forced_candidate_on_every_reference_token": True,
    }


def _paired_fixed_history_cost_control(
    model,
    embedding_weight: torch.Tensor,
    reference_output,
    reference_position: int,
    candidate_output,
    candidate_position: int,
    *,
    token_id: int,
    horizon: int,
) -> dict[str, Any]:
    """Force one non-EOS token for a full-length compute ceiling control."""

    if not 0 <= token_id < MODEL_VOCAB_SIZE:
        raise ValueError("fixed cost-control token is outside the model vocabulary")
    reference_logits: list[torch.Tensor] = []
    candidate_logits: list[torch.Tensor] = []
    ref_current = reference_output
    cand_current = candidate_output
    token_embedding = embedding_weight[token_id]
    for _ in range(horizon):
        reference_logits.append(ref_current.logits[0, -1].detach())
        candidate_logits.append(cand_current.logits[0, -1].detach())
        ref_current = _step(
            model, ref_current.past_key_values, token_embedding, reference_position
        )
        cand_current = _step(
            model, cand_current.past_key_values, token_embedding, candidate_position
        )
        reference_position += 1
        candidate_position += 1
    path_kl = paired_path_kl(torch.stack(reference_logits), torch.stack(candidate_logits))
    return {
        "scientific_result": False,
        "history_policy": "fixed non-EOS token repeated for a full-length compute control",
        "forced_token_id": token_id,
        "horizon": horizon,
        "per_step_directional_kl": path_kl.per_step.detach().cpu().tolist(),
        "sum_directional_kl": path_kl.total,
    }


def run_preflight(*, benchmark_horizon: int | None = None) -> ForwardActionPreflightResult:
    if benchmark_horizon is not None and benchmark_horizon < 1:
        raise ValueError("benchmark_horizon must be positive")
    started = time.perf_counter()
    failures: list[str] = []
    runtime = {
        "torch": torch.__version__,
        "transformers": transformers_version,
        "model_dir": str(MODEL_DIR),
        "cuda_available": torch.cuda.is_available(),
    }
    protocol = {
        "scope": "endpoint-aware Family-A no-JVP source-action preflight",
        "no_dataset_or_calibration": True,
        "action_seeds": list(ACTION_SEEDS),
        "reference_first_action": "pinned official no-noise latent sampler, top-k=10",
        "candidate_first_action": "pinned official Gumbel latent sampler, top-k=10",
        "natural_suffix_policy": (
            "persistent source request, candidate-owned cache, no-noise source sampler, "
            f"natural endpoint or cap={NATURAL_LATENT_CAP}"
        ),
        "plumbing_control": (
            f"cap={CONTROL_LATENT_STEPS} then explicitly labeled forced E_524"
        ),
        "visible_policy": (
            "fixed-seed full-vocabulary temperature-1 sampling plus same-history teacher forcing"
        ),
        "benchmark_horizon": benchmark_horizon,
        "not_authorized": [
            "P1 phenomenon claim",
            "Horizon Gap score",
            "calibration",
            "held-out experiment",
            "PaTR implementation",
            "training",
        ],
    }
    if not torch.cuda.is_available():
        return ForwardActionPreflightResult(
            "BLOCKED_NO_CUDA", runtime, protocol, {}, [], {}, {}, {}, {}, {},
            ["CUDA unavailable"],
        )

    torch.cuda.empty_cache()
    torch.cuda.reset_peak_memory_stats()
    tokenizer = AutoTokenizer.from_pretrained(MODEL_DIR, local_files_only=True, use_fast=True)
    # The source request checks this tokenizer-owned stop set in addition to
    # model EOS and user-supplied stops, so the actual request replay must add
    # it before any first-action admissibility decision.
    from sglang.srt.hf_transformers_utils import attach_additional_stop_token_ids

    attach_additional_stop_token_ids(tokenizer)
    prompt_text = tokenizer.apply_chat_template(
        [{"role": "user", "content": PROMPT_USER_TEXT}],
        tokenize=False,
        add_generation_prompt=True,
    )
    prompt_ids = tuple(tokenizer(prompt_text, add_special_tokens=False)["input_ids"])
    prompt = {
        "name": PROMPT_NAME,
        "construction": "checkpoint chat_template with one synthetic user message",
        "text": prompt_text,
        "token_ids": list(prompt_ids),
        "source_end_id": SOURCE_END_ID,
        "source_end_decode": tokenizer.decode([SOURCE_END_ID]),
        "eos_token_id": int(tokenizer.eos_token_id),
    }
    if any(token_id < 0 or token_id >= MODEL_VOCAB_SIZE for token_id in prompt_ids):
        failures.append("synthetic prompt contains a tokenizer-only token id")
    if not prompt_text.rstrip().endswith("<think>"):
        failures.append("source-format synthetic prompt does not end with <think>")
    if SOURCE_END_ID == tokenizer.eos_token_id or SOURCE_END_ID in tokenizer.all_special_ids:
        failures.append("source 524 boundary is an EOS/special token")

    model = None
    action_bank: list[dict[str, Any]] = []
    endpoint_audit: dict[str, Any] = {}
    identity_control: dict[str, Any] = {}
    paired_forward_path: dict[str, Any] = {}
    timing: dict[str, Any] = {}
    try:
        load_started = time.perf_counter()
        _progress("loading frozen local checkpoint")
        model = AutoModelForCausalLM.from_pretrained(
            MODEL_DIR,
            torch_dtype=torch.bfloat16,
            low_cpu_mem_usage=True,
            local_files_only=True,
        ).to("cuda").eval()
        for parameter in model.parameters():
            parameter.requires_grad_(False)
        embedding_weight = model.get_input_embeddings().weight
        timing["model_load_seconds"] = time.perf_counter() - load_started

        with torch.inference_mode():
            action_started = time.perf_counter()
            _progress("checking deterministic synthetic prefill")
            prefill_a = _prefill(model, prompt_ids)
            prefill_b = _prefill(model, prompt_ids)
            repeat_error = float((prefill_a.logits - prefill_b.logits).abs().max().item())
            if repeat_error != 0.0:
                failures.append("repeated synthetic prefill is not bit-identical")

            reference_proposal = replay_pinned_sampler_on_fake_request(
                prefill_a.logits[0, -1], _sampler_config(noise=False)
            )
            reference_execution = _execute_under_actual_request(
                tokenizer, reference_proposal, "reference-first"
            )
            reference_embedding = _source_weighted_embedding(
                embedding_weight,
                reference_proposal.topk_indices,
                reference_proposal.topk_probs,
            )
            action_bank.append(
                {
                    "role": "deterministic_reference",
                    "seed": None,
                    "proxy": reference_proposal.next_token_id,
                    "topk_ids": [
                        int(value)
                        for value in reference_proposal.topk_indices.detach().cpu().tolist()
                    ],
                    "topk_probs": _as_list(reference_proposal.topk_probs),
                    "continuous_action_consumed": reference_execution[
                        "continuous_action_consumed"
                    ],
                    "structural_end_consumed": reference_execution[
                        "structural_end_consumed"
                    ],
                    "finished_after_check": reference_execution["finished_after_check"],
                    "latent_mode_after_update": reference_execution["latent_mode_after_update"],
                    "source_weighted_embedding_norm": float(
                        reference_embedding.float().norm().item()
                    ),
                    "l2_to_reference": 0.0,
                }
            )
            if not reference_execution["continuous_action_consumed"]:
                failures.append("deterministic reference is not a consumable latent action")

            candidate_actions: list[
                tuple[int, OfficialSamplerReplay, torch.Tensor, dict[str, Any]]
            ] = []
            for seed in ACTION_SEEDS:
                _progress(f"replaying fixed source action seed={seed}")
                proposal = _sample_source_action(prefill_a.logits[0, -1], seed)
                execution = _execute_under_actual_request(tokenizer, proposal, f"first-{seed}")
                source_embedding = _source_weighted_embedding(
                    embedding_weight, proposal.topk_indices, proposal.topk_probs
                )
                legacy_embedding = _legacy_bf16_first_embedding(
                    embedding_weight, proposal.topk_indices, proposal.topk_probs
                )
                entry = {
                    "role": "noisy_candidate",
                    "seed": seed,
                    "proxy": proposal.next_token_id,
                    "topk_ids": [int(value) for value in proposal.topk_indices.detach().cpu().tolist()],
                    "topk_probs": _as_list(proposal.topk_probs),
                    "topk_gumbel_scores": _as_list(proposal.topk_gumbels),
                    "continuous_action_consumed": execution["continuous_action_consumed"],
                    "structural_end_consumed": execution["structural_end_consumed"],
                    "finished_after_check": execution["finished_after_check"],
                    "latent_mode_after_update": execution["latent_mode_after_update"],
                    "source_weighted_embedding_norm": float(source_embedding.float().norm().item()),
                    "legacy_bf16_first_max_abs_difference": float(
                        (source_embedding.float() - legacy_embedding.float()).abs().max().item()
                    ),
                    "l2_to_reference": float(
                        (source_embedding.float() - reference_embedding.float()).norm().item()
                    ),
                }
                action_bank.append(entry)
                if (
                    execution["continuous_action_consumed"]
                    and entry["l2_to_reference"] >= MIN_DISTINCT_ACTION_L2
                ):
                    candidate_actions.append((seed, proposal, source_embedding, execution))

            timing["action_bank_seconds"] = time.perf_counter() - action_started
            if not candidate_actions:
                failures.append("no fixed-seed noisy candidate is consumable and distinct")

            if reference_execution["continuous_action_consumed"] and candidate_actions and not failures:
                candidate_seed, candidate_proposal, candidate_embedding, _ = candidate_actions[0]

                def fresh_closure(
                    proposal: OfficialSamplerReplay,
                    rid: str,
                    *,
                    latent_cap: int,
                    force_visible_control: bool,
                ) -> tuple[Any, int, dict[str, Any]]:
                    return _close_source_action(
                        model,
                        tokenizer,
                        embedding_weight,
                        _prefill(model, prompt_ids),
                        len(prompt_ids),
                        proposal,
                        rid,
                        latent_cap=latent_cap,
                        force_visible_control=force_visible_control,
                    )

                natural_started = time.perf_counter()
                _progress("auditing natural persistent-request closures")
                natural_ref_output, natural_ref_position, natural_ref = fresh_closure(
                    reference_proposal,
                    "natural-reference",
                    latent_cap=NATURAL_LATENT_CAP,
                    force_visible_control=False,
                )
                natural_cand_output, natural_cand_position, natural_cand = fresh_closure(
                    candidate_proposal,
                    f"natural-candidate-{candidate_seed}",
                    latent_cap=NATURAL_LATENT_CAP,
                    force_visible_control=False,
                )
                natural_pair = audit_endpoint_pair(
                    ContinuationEndpoint(natural_ref["endpoint"]),
                    ContinuationEndpoint(natural_cand["endpoint"]),
                )
                natural_cache_disjoint = not bool(
                    set(_cache_ptrs(natural_ref_output.past_key_values))
                    & set(_cache_ptrs(natural_cand_output.past_key_values))
                )
                if not natural_cache_disjoint:
                    failures.append("natural reference and candidate share KV-cache storage")
                endpoint_audit["natural_pair"] = {
                    **asdict(natural_pair),
                    "reference_closure": natural_ref,
                    "candidate_closure": natural_cand,
                    "cache_storage_disjoint": natural_cache_disjoint,
                }
                timing["natural_closure_seconds"] = time.perf_counter() - natural_started

                control_started = time.perf_counter()
                _progress("building forced-boundary identity and plumbing controls")
                control_ref_a_output, control_ref_a_position, control_ref_a = fresh_closure(
                    reference_proposal,
                    "control-reference-a",
                    latent_cap=CONTROL_LATENT_STEPS,
                    force_visible_control=True,
                )
                control_ref_b_output, control_ref_b_position, control_ref_b = fresh_closure(
                    reference_proposal,
                    "control-reference-b",
                    latent_cap=CONTROL_LATENT_STEPS,
                    force_visible_control=True,
                )
                control_cand_output, control_cand_position, control_cand = fresh_closure(
                    candidate_proposal,
                    f"control-candidate-{candidate_seed}",
                    latent_cap=CONTROL_LATENT_STEPS,
                    force_visible_control=True,
                )
                control_audit = audit_endpoint_pair(
                    ContinuationEndpoint(control_ref_a["endpoint"]),
                    ContinuationEndpoint(control_cand["endpoint"]),
                    allow_forced_control=True,
                )
                endpoint_audit["plumbing_control_pair"] = {
                    **asdict(control_audit),
                    "reference_closure": control_ref_a,
                    "candidate_closure": control_cand,
                }

                identity_forward = _paired_visible_sample_and_force(
                    model,
                    embedding_weight,
                    control_ref_a_output,
                    control_ref_a_position,
                    control_ref_b_output,
                    control_ref_b_position,
                    int(tokenizer.eos_token_id),
                    sample_seed=VISIBLE_IDENTITY_SEED,
                    horizon=VISIBLE_TEST_HORIZON,
                )
                identity_rev_left, identity_rev_left_pos, _ = fresh_closure(
                    reference_proposal,
                    "identity-reverse-left",
                    latent_cap=CONTROL_LATENT_STEPS,
                    force_visible_control=True,
                )
                identity_rev_right, identity_rev_right_pos, _ = fresh_closure(
                    reference_proposal,
                    "identity-reverse-right",
                    latent_cap=CONTROL_LATENT_STEPS,
                    force_visible_control=True,
                )
                identity_reverse = _paired_visible_sample_and_force(
                    model,
                    embedding_weight,
                    identity_rev_left,
                    identity_rev_left_pos,
                    identity_rev_right,
                    identity_rev_right_pos,
                    int(tokenizer.eos_token_id),
                    sample_seed=VISIBLE_IDENTITY_SEED + 1,
                    horizon=VISIBLE_TEST_HORIZON,
                )
                identity_cache_disjoint = not bool(
                    set(_cache_ptrs(control_ref_a_output.past_key_values))
                    & set(_cache_ptrs(control_ref_b_output.past_key_values))
                )
                identity_max = max(
                    identity_forward["per_step_directional_kl"]
                    + identity_reverse["per_step_directional_kl"]
                )
                identity_pass = bool(
                    identity_cache_disjoint
                    and identity_max <= IDENTITY_KL_TOLERANCE
                    and identity_forward["sum_directional_kl"] <= IDENTITY_KL_TOLERANCE
                    and identity_reverse["sum_directional_kl"] <= IDENTITY_KL_TOLERANCE
                )
                identity_control = {
                    "status": "PASS" if identity_pass else "FAIL",
                    "cache_storage_disjoint": identity_cache_disjoint,
                    "tolerance": IDENTITY_KL_TOLERANCE,
                    "max_per_step_kl": identity_max,
                    "forward": identity_forward,
                    "reverse": identity_reverse,
                }
                if not identity_pass:
                    failures.append("independent-cache identity control is not zero")

                control_fwd_ref, control_fwd_ref_pos, _ = fresh_closure(
                    reference_proposal,
                    "control-forward-reference",
                    latent_cap=CONTROL_LATENT_STEPS,
                    force_visible_control=True,
                )
                control_fwd_cand, control_fwd_cand_pos, _ = fresh_closure(
                    candidate_proposal,
                    "control-forward-candidate",
                    latent_cap=CONTROL_LATENT_STEPS,
                    force_visible_control=True,
                )
                control_forward = _paired_visible_sample_and_force(
                    model,
                    embedding_weight,
                    control_fwd_ref,
                    control_fwd_ref_pos,
                    control_fwd_cand,
                    control_fwd_cand_pos,
                    int(tokenizer.eos_token_id),
                    sample_seed=VISIBLE_FORWARD_SEED,
                    horizon=VISIBLE_TEST_HORIZON,
                )
                control_rev_cand, control_rev_cand_pos, _ = fresh_closure(
                    candidate_proposal,
                    "control-reverse-candidate",
                    latent_cap=CONTROL_LATENT_STEPS,
                    force_visible_control=True,
                )
                control_rev_ref, control_rev_ref_pos, _ = fresh_closure(
                    reference_proposal,
                    "control-reverse-reference",
                    latent_cap=CONTROL_LATENT_STEPS,
                    force_visible_control=True,
                )
                control_reverse = _paired_visible_sample_and_force(
                    model,
                    embedding_weight,
                    control_rev_cand,
                    control_rev_cand_pos,
                    control_rev_ref,
                    control_rev_ref_pos,
                    int(tokenizer.eos_token_id),
                    sample_seed=VISIBLE_REVERSE_SEED,
                    horizon=VISIBLE_TEST_HORIZON,
                )
                paired_forward_path["plumbing_control"] = {
                    "scientific_evidence": False,
                    "reason": "at least one branch uses an explicitly forced E_524 boundary",
                    "candidate_seed": candidate_seed,
                    "initial_action_l2": float(
                        (candidate_embedding.float() - reference_embedding.float()).norm().item()
                    ),
                    "forward": control_forward,
                    "reverse": control_reverse,
                }
                timing["plumbing_and_identity_seconds"] = time.perf_counter() - control_started

                if natural_pair.scientific_visible_pair:
                    scientific_started = time.perf_counter()
                    _progress("evaluating natural bidirectional same-history paths")
                    natural_fwd_ref, natural_fwd_ref_pos, natural_fwd_ref_meta = fresh_closure(
                        reference_proposal,
                        "natural-forward-reference",
                        latent_cap=NATURAL_LATENT_CAP,
                        force_visible_control=False,
                    )
                    natural_fwd_cand, natural_fwd_cand_pos, natural_fwd_cand_meta = fresh_closure(
                        candidate_proposal,
                        "natural-forward-candidate",
                        latent_cap=NATURAL_LATENT_CAP,
                        force_visible_control=False,
                    )
                    if not (
                        natural_fwd_ref_meta["natural_visible"]
                        and natural_fwd_cand_meta["natural_visible"]
                    ):
                        raise RuntimeError("fresh natural forward closures changed endpoint")
                    natural_forward = _paired_visible_sample_and_force(
                        model,
                        embedding_weight,
                        natural_fwd_ref,
                        natural_fwd_ref_pos,
                        natural_fwd_cand,
                        natural_fwd_cand_pos,
                        int(tokenizer.eos_token_id),
                        sample_seed=VISIBLE_FORWARD_SEED,
                        horizon=VISIBLE_TEST_HORIZON,
                    )
                    natural_rev_cand, natural_rev_cand_pos, natural_rev_cand_meta = fresh_closure(
                        candidate_proposal,
                        "natural-reverse-candidate",
                        latent_cap=NATURAL_LATENT_CAP,
                        force_visible_control=False,
                    )
                    natural_rev_ref, natural_rev_ref_pos, natural_rev_ref_meta = fresh_closure(
                        reference_proposal,
                        "natural-reverse-reference",
                        latent_cap=NATURAL_LATENT_CAP,
                        force_visible_control=False,
                    )
                    if not (
                        natural_rev_cand_meta["natural_visible"]
                        and natural_rev_ref_meta["natural_visible"]
                    ):
                        raise RuntimeError("fresh natural reverse closures changed endpoint")
                    natural_reverse = _paired_visible_sample_and_force(
                        model,
                        embedding_weight,
                        natural_rev_cand,
                        natural_rev_cand_pos,
                        natural_rev_ref,
                        natural_rev_ref_pos,
                        int(tokenizer.eos_token_id),
                        sample_seed=VISIBLE_REVERSE_SEED,
                        horizon=VISIBLE_TEST_HORIZON,
                    )
                    paired_forward_path["natural_pair"] = {
                        "scientific_estimand_candidate": True,
                        "candidate_seed": candidate_seed,
                        "forward": natural_forward,
                        "reverse": natural_reverse,
                    }
                    timing["natural_visible_h4_seconds"] = (
                        time.perf_counter() - scientific_started
                    )

                    if benchmark_horizon is not None:
                        benchmark_started = time.perf_counter()
                        benchmark_ref, benchmark_ref_pos, benchmark_ref_meta = fresh_closure(
                            reference_proposal,
                            "benchmark-reference",
                            latent_cap=NATURAL_LATENT_CAP,
                            force_visible_control=False,
                        )
                        benchmark_cand, benchmark_cand_pos, benchmark_cand_meta = fresh_closure(
                            candidate_proposal,
                            "benchmark-candidate",
                            latent_cap=NATURAL_LATENT_CAP,
                            force_visible_control=False,
                        )
                        if not (
                            benchmark_ref_meta["natural_visible"]
                            and benchmark_cand_meta["natural_visible"]
                        ):
                            raise RuntimeError("benchmark natural closures changed endpoint")
                        visible_started = time.perf_counter()
                        benchmark_forward = _paired_visible_sample_and_force(
                            model,
                            embedding_weight,
                            benchmark_ref,
                            benchmark_ref_pos,
                            benchmark_cand,
                            benchmark_cand_pos,
                            int(tokenizer.eos_token_id),
                            sample_seed=VISIBLE_BENCHMARK_SEED,
                            horizon=benchmark_horizon,
                        )
                        visible_seconds = time.perf_counter() - visible_started
                        valid_steps = len(benchmark_forward["per_step_directional_kl"])
                        sampled_total_seconds = time.perf_counter() - benchmark_started
                        fixed_ref, fixed_ref_pos, fixed_ref_meta = fresh_closure(
                            reference_proposal,
                            "benchmark-fixed-reference",
                            latent_cap=NATURAL_LATENT_CAP,
                            force_visible_control=False,
                        )
                        fixed_cand, fixed_cand_pos, fixed_cand_meta = fresh_closure(
                            candidate_proposal,
                            "benchmark-fixed-candidate",
                            latent_cap=NATURAL_LATENT_CAP,
                            force_visible_control=False,
                        )
                        if not (
                            fixed_ref_meta["natural_visible"]
                            and fixed_cand_meta["natural_visible"]
                        ):
                            raise RuntimeError("fixed-history benchmark closures changed endpoint")
                        fixed_visible_started = time.perf_counter()
                        fixed_control = _paired_fixed_history_cost_control(
                            model,
                            embedding_weight,
                            fixed_ref,
                            fixed_ref_pos,
                            fixed_cand,
                            fixed_cand_pos,
                            token_id=BENCHMARK_FORCE_TOKEN_ID,
                            horizon=benchmark_horizon,
                        )
                        fixed_visible_seconds = time.perf_counter() - fixed_visible_started
                        total_benchmark_seconds = time.perf_counter() - benchmark_started
                        paired_forward_path["single_unit_microbenchmark"] = {
                            "scientific_result": False,
                            "purpose": "cost measurement only",
                            "requested_horizon": benchmark_horizon,
                            "valid_visible_steps": valid_steps,
                            "natural_reference_latent_steps": len(
                                benchmark_ref_meta["records"]
                            ),
                            "natural_candidate_latent_steps": len(
                                benchmark_cand_meta["records"]
                            ),
                            "visible_sample_and_force_seconds": visible_seconds,
                            "sampled_total_with_fresh_closures_seconds": sampled_total_seconds,
                            "visible_steps_per_second": (
                                valid_steps / visible_seconds if visible_seconds > 0 else None
                            ),
                            "sampled_forward": benchmark_forward,
                            "full_length_cost_control": {
                                "visible_sample_and_force_seconds": fixed_visible_seconds,
                                "visible_steps_per_second": (
                                    benchmark_horizon / fixed_visible_seconds
                                    if fixed_visible_seconds > 0
                                    else None
                                ),
                                "result": fixed_control,
                            },
                            "total_benchmark_seconds": total_benchmark_seconds,
                        }
                        timing["single_unit_microbenchmark_seconds"] = total_benchmark_seconds

                paired_forward_path["prefill_repeat_max_abs_error"] = repeat_error

        gpu = {
            "peak_allocated_bytes": int(torch.cuda.max_memory_allocated()),
            "peak_reserved_bytes": int(torch.cuda.max_memory_reserved()),
            "free_bytes_after_preflight": int(torch.cuda.mem_get_info()[0]),
        }
        natural_ok = bool(
            endpoint_audit.get("natural_pair", {}).get("scientific_visible_pair", False)
        )
        if failures:
            status = "FAIL-FORWARD-KL-PREFLIGHT"
        elif natural_ok:
            status = "PASS-NATURAL-FORWARD-KL-PREFLIGHT"
        else:
            status = "PASS-PLUMBING-HOLD-NATURAL-CLOSURE"
        timing["total_seconds"] = time.perf_counter() - started
        _progress(f"finished with status={status}")
        return ForwardActionPreflightResult(
            status,
            runtime,
            protocol,
            prompt,
            action_bank,
            endpoint_audit,
            identity_control,
            paired_forward_path,
            timing,
            gpu,
            failures,
        )
    except torch.OutOfMemoryError as exc:
        torch.cuda.empty_cache()
        return ForwardActionPreflightResult(
            "OOM", runtime, protocol, prompt, action_bank, endpoint_audit,
            identity_control, paired_forward_path, timing, {},
            [f"model preflight OOM: {exc}"[:500]],
        )
    except Exception as exc:
        return ForwardActionPreflightResult(
            "ERROR", runtime, protocol, prompt, action_bank, endpoint_audit,
            identity_control, paired_forward_path, timing, {},
            [f"{type(exc).__name__}: {exc}"[:500]],
        )
    finally:
        if model is not None:
            del model
        torch.cuda.empty_cache()


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--benchmark-horizon",
        type=int,
        default=None,
        help="run one additional natural forward-only cost unit at this visible horizon",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=None,
        help="optional UTF-8 JSON path for the complete machine-readable result",
    )
    args = parser.parse_args()
    payload = json.dumps(
        asdict(run_preflight(benchmark_horizon=args.benchmark_horizon)),
        ensure_ascii=False,
        indent=2,
        sort_keys=True,
    )
    if args.output is not None:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(payload + "\n", encoding="utf-8")
    print(payload)
